const prodinfo=[
    {
        key:1,
        ImgName:"../assets/Productimgs/z1.jpg",
        category:"women",
        Pname:"T-SHIRT",
        price:"₹1,590.00",
        descr:"STRIPED T-SHIRT",
    },
    {
        key:2,
        ImgName:"../assets/Productimgs/z2.jpg",
        category:"women",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
    {
        key:3,
        ImgName:"../assets/Productimgs/z6.jpg",
        category:"men",
        Pname:"SWEATSHIRT",
        price:"₹4,000.00",
        descr:"TIED SHIRT",
    },
    {
        key:4,
        ImgName:"../assets/Productimgs/z4.jpg",
        category:"women",
        Pname:"T-SHIRT",
        price:"₹4,000.00",
        descr:"TIED SHIRT",
    },
    {
        key:5,
       
        ImgName:"../assets/Productimgs/z5.jpg",
        category:"men",
        Pname:"SWEATSHIRT",
        price:"₹4,000.00",
        descr:"TIED SHIRT",
    },
    {
        key:6,
       
        ImgName:"../assets/Productimgs/z3.jpg",
        category:"women",
        Pname:"T-SHIRT",
        price:"₹4,000.00",
        descr:"TIED SHIRT",
    },
    {
        key:7,
      
        ImgName:"../assets/Productimgs/z7.jpg",
        category:"men",
        Pname:"SWEATSHIRT",
        price:"₹4,000.00",
        descr:"TIED SHIRT",
    },
    {
        key:8,
       
        ImgName:"../assets/Productimgs/z8.jpg",
        category:"men",
        Pname:"T-SHIRT",
        price:"₹4,000.00",
        descr:"TIED SHIRT",
    },
 
    {
        key:9,
        ImgName:"../assets/Productimgs/z9w.webp",
        category:"women",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
    {
        key:10,
        ImgName:"../assets/Productimgs/z10w.webp",
        category:"women",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
    {
        key:11,
        ImgName:"../assets/Productimgs/z11w.webp",
        category:"women",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
    {
        key:12,
        ImgName:"../assets/Productimgs/z12w.jpg",
        category:"women",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
    {
        key:13,
        ImgName:"../assets/Productimgs/z13w.jpg",
        category:"women",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
    {
        key:13,
        ImgName:"../assets/Productimgs/z14w.jpg",
        category:"kids",
        Pname:"SHIRT",
        price:"₹2,000.00",
        descr:"BEADED POPLIN SHIRT",
    },
];

export default prodinfo;